---
title: "PerfComparison"
output: html_notebook
---

###Setup, libraries
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = 'C:/Users/tijs/Documents/RademakersLab/R')

```

```{r}
setwd("C:/Users/tijs/Documents/RademakersLab/R")


#Loading libraries
library(tidyverse)
library(stringi)
library(stringr)
library(data.table)
library(gtools)
library("EnhancedVolcano")
library(tibble)
library(dplyr)
library(eulerr)
library(conflicted) #Decide between functions that overlap between packages
library(RColorBrewer)
library(ggvenn)
library(ggVennDiagram)
library(VennDiagram)

```

###Name CyrilData different than mine
```{r}
#f1_linear<-f1_output
#RPKM_linear<-RPKM.cqn_prot
#sampleinfolin<-sampleinfo

#rm(f1_output, RPKM.cqn_prot, sampleinfo)

f1_linear$Log2FC<-foldchange2logratio(f1_linear$FoldChangeTDP_vs_Control, base=2)

head(f1_linear)

```

###Choosing colors
```{r}

display.brewer.pal(n = 10, name = 'Paired')
brewer.pal(n = 10, name = 'Paired')
display.brewer.pal(n = 9, name = "Set1" )
brewer.pal(n = 9, name = "Set1" )
#"#A6CEE3" "#1F78B4" "#B2DF8A" "#33A02C" "#FB9A99" "#E31A1C" "#FDBF6F" "#FF7F00" "#CAB2D6" "#6A3D9A"

```

###Now load own data, and don't rerun previous lines!!
###Compare data from both aligners
```{r}

options( stringsAsFactors = FALSE)
venni <- list(`Graphbased` = Expression_data$symbol,
              `Linear` = as.character(f1_linear$symbol))


#VennDiagram package
#Venn diagram of all genes found in gene count analysis
overlap<-calculate.overlap(x=venni)

vennplot<-draw.pairwise.venn(area1 = 17933,
                   area2 = 15970,
                   cross.area = 15592,
                   main= "Identified genes" ,
                   category = c("HISAT2","STAR"),
                   #fill=c("#99CCFF", "#CC33CC"),
                   fill=c("#1F78B4", "#FF7F00"),
                   alpha = 0.4,
                   #col=c("#99CCFF", "#CC33CC"),
                   col= c("#1F78B4", "#FF7F00"),
                   lwd=1,
                   euler.d=TRUE,
                   scaled = TRUE,
                   print.mode = c("raw","percent"),
                   cex = 1.1,
                   cat.cex = 1.3,
                   cat.dist = c(0.03,0.03),
                   ext.text = FALSE,
                   rotation.degree=30,
                   )
grid.draw(vennplot)
                   

#onlyoverlap<-overlap$a3

```


###Plotting log2FC for all found genes and then for found HLA genes only
```{r}
#First make comparison between STAR and HISAT2 for all common found genes

matches3<-merge(Expression_data, f1_linear, by.x="GeneSymbol", by.y="GeneId")
matches1<-Expression_data %>% filter(GeneSymbol %in% f1_linear$GeneId )

#custom colors preparation: make column with absolute value of the difference between both log values
matches3$diff <- abs(matches3$Log2FC.x - matches3$Log2FC.y)
mp=mean(matches3$diff)

#color is a gradient
g1<-ggplot(matches3, aes(Log2FC.x, Log2FC.y, color=diff)) +
      geom_point() + 
      geom_smooth(method="lm", se=F, color="orangered3" ) +
      labs(subtitle="Expression of overlapping genes", y="Log2FC (lin)", x="log2FC (gb)", title="STAR (lin) vs. HISAT2 (gb)", caption="Comparison of log2 fold change between Linear and Graph-based expression data")

g1
g1 + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))

#customize colors for gradient here
g1 + scale_color_gradient2(midpoint=mp, low="turquoise1", mid="royalblue", high="navy")


#custom colors preparation: make factorized column
max(matches3$diff)
min(matches3$diff)
#max is 1.54
matches3 <- matches3 %>% mutate(factor=case_when(diff<=0.4 ~ "0.4",
                                                 diff>0.4 & diff<=0.9 ~ "0.9",
                                                 diff>0.9 ~ "1.6"))

#colors in intervals  
g2<-ggplot(matches3, aes(Log2FC.x, Log2FC.y, color=factor)) +
      geom_point() + 
      theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
      geom_smooth(method="lm", se=F, color="#1A1A1A" ) +
      labs(subtitle="Expression of overlapping genes", y="Log2FC (lin)", x="log2FC (gb)", title="STAR (lin) vs. HISAT2 (gb)", caption="Comparison of log2 fold change between Linear and Graph-based expression data")

#custom colors here
g2 + scale_color_manual(values= c("#4393C3", "#2166AC", "#053061"))
g2 + scale_color_manual(values= c("#D6604D", "#B2182B", "#67001F"))
g2 + scale_color_manual(values= c("#B2182B", "#67001F", "#1A1A1A"))

```

```{r}

#Here I wanna plot the fold change ot gene expression found for the HLA genes comparing both aligners

options( stringsAsFactors = FALSE)

cmpr<-Expression_data [grepl (c("HLA-"), Expression_data$symbol) , ]
cmprl<-f1_linear [grepl (c("HLA-"), f1_linear$symbol) , ]
cmprHLA<- merge(cmpr, cmprl, by.x = "symbol", by.y = "symbol")
cmprHLA<-cmprHLA[, c(1,3,4,5,7,21:24)]
rm(cmpr,cmprl)

ggplot(cmprHLA, aes(Log2FC.x, Log2FC.y)) +
      geom_point(color="red") +
      ylim(-0.3,1.6) +
      theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
      geom_label_repel(aes(label=symbol),colour="black", size=3, lineheight=0.7, max.overlaps = Inf ) +
      geom_smooth(method="lm", se=F, color="black" ) +
      labs(y="Log2FC (lin)", x="log2FC (gb)", title="STAR (lin) vs. HISAT2 (gb) for HLA genes", caption="Comparison of log2 fold change between
           Linear and Graph-based expression data for the HLA genes")



g1 + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=2)) +
  geom_point(data = matches3 %>% filter(str_detect(symbol.x, "HLA-")), color = "red", size =2)



  

display.brewer.pal(n = 10, name = 'RdBu')
brewer.pal(n = 10, name = 'RdBu')
display.brewer.pal(n = 10, name = "RdGy" )
brewer.pal(n = 10, name = "RdGy" )

```


```{r}

V1<- EnhancedVolcano(Expression_data,
    lab = as.character(Expression_data$symbol),
    x = 'Log2FC',
    y = 'Pvalue_fdr',
    xlim = c(min(Expression_data[["Log2FC"]], na.rm = TRUE) - 2.0, max(Expression_data[["Log2FC"]], na.rm = TRUE) +
2.0),
    ylim = c(0, max(-log10(Expression_data[["Pvalue_fdr"]]), na.rm = TRUE) + 0.5),
    axisLabSize = 10.0,
    title = 'DGE TDP vs Controls',
    titleLabSize = 13.0,
    subtitle = 'HISAT2',
    subtitleLabSize = 10.0,
    captionLabSize = 9.0,
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 0.1,
    labSize = 3.5,
    labCol = "black",
    #drawConnectors = TRUE,
    #widthConnectors = 0.5,
    col=c("#CAB2D6", "#FDBF6F", "#1F78B4", "#FF7F00" ),
    colAlpha = 0.75,
    legendLabels=c('Not significant',expression(Log[2]~FC), expression(italic (p-value)),  expression(italic(p)~and~Log[2]~FC)),
    legendPosition = 'right',
    legendLabSize = 10,
    legendIconSize = 2.0,
    gridlines.major = TRUE,
    gridlines.minor = TRUE,
    border = "full",
    borderWidth = 0.5)

 V2<-EnhancedVolcano(f1_linear,
    lab = as.character(f1_linear$symbol),
    x = 'Log2FC',
    y = 'PValueTDP_vs_Control_adj',
    xlim = c(min(f1_linear[["Log2FC"]], na.rm = TRUE) - 2.0, max(f1_linear[["Log2FC"]], na.rm = TRUE) +
2.0),
    ylim = c(0, max(-log10(f1_linear[["PValueTDP_vs_Control_adj"]]), na.rm = TRUE) + 0.5),
    axisLabSize = 10.0,
    title = 'DGE TDP vs Controls',
    titleLabSize = 13.0,
    subtitle = 'STAR',
    subtitleLabSize = 10.0,
    captionLabSize = 9.0,
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 0.1,
    labSize = 3.5,
    labCol = "black",
    #drawConnectors = TRUE,
    #widthConnectors = 0.5,
    col=c("#CAB2D6", "#FDBF6F", "#1F78B4", "#FF7F00" ),
    colAlpha = 0.75,
    legendLabels=c('Not significant',expression(Log[2]~FC), expression(italic (p-value)),  expression(italic(p)~and~Log[2]~FC)),
    legendPosition = 'right',
    legendLabSize = 10,
    legendIconSize = 2.0,
    gridlines.major = TRUE,
    gridlines.minor = TRUE,
    border = "full",
    borderWidth = 0.5)
 
 
 V3<-EnhancedVolcano(f1_linear,
    lab = as.character(f1_linear$symbol),
    x = 'Log2FC',
    y = 'PValueTDP_vs_Control_adj',
    xlim = c(min(f1_linear[["Log2FC"]], na.rm = TRUE) - 2.0, max(f1_linear[["Log2FC"]], na.rm = TRUE) +
2.0),
    ylim = c(0, max(-log10(Expression_data[["Pvalue_fdr"]]), na.rm = TRUE) + 0.5),
    axisLabSize = 10.0,
    title = 'DGE TDP vs Controls',
    titleLabSize = 13.0,
    subtitle = 'STAR',
    subtitleLabSize = 10.0,
    captionLabSize = 9.0,
    pCutoff = 0.05,
    FCcutoff = 1.0,
    pointSize = 0.1,
    labSize = 3.5,
    labCol = "black",
    #drawConnectors = TRUE,
    #widthConnectors = 0.5,
    col=c("#CAB2D6", "#FDBF6F", "#1F78B4", "#FF7F00" ),
    colAlpha = 0.75,
    legendLabels=c('Not significant',expression(Log[2]~FC), expression(italic (p-value)),  expression(italic(p)~and~Log[2]~FC)),
    legendPosition = 'right',
    legendLabSize = 10,
    legendIconSize = 2.0,
    gridlines.major = TRUE,
    gridlines.minor = TRUE,
    border = "full",
    borderWidth = 0.5)

V1 + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())
V2 + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())
V3 + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())

```

###Venn diagram of all significant genes in DGE analysis
```{r}

f1_linlim<-f1_linear[,c(1,2,14,15,16,17)]
DGlin<-subset(f1_linlim, f1_linlim$PValueTDP_vs_Control_adj < 0.05)
DGgr<-subset(Expression_data, Expression_data$Pvalue_fdr < 0.05 )

venni2 <- list(`gbsig` = DGgr$symbol,
              `linsig` = as.character(DGlin$symbol))

overlap<-calculate.overlap(x=venni2)
#7656 (gb), 5636 (lin), 5398

vennplot2<-draw.pairwise.venn(area1 = 7656,
                   area2 = 5636,
                   cross.area = 5398,
                   main= "Identified genes" ,
                   category = c("HISAT2","STAR"),
                   #fill=c("#99CCFF", "#CC33CC"),
                   fill=c("#1F78B4", "#FF7F00"),
                   alpha = 0.4,
                   print.mode = c("raw","percent"),
                   #col=c("#99CCFF", "#CC33CC"),
                   col= c("#1F78B4", "#FF7F00"),
                   lwd=1,
                   euler.d=TRUE,
                   scaled = TRUE,
                   ext.text = FALSE,
                   rotation.degree=30,
                   )
grid.draw(vennplot2)

```
















